# Generated by Django 4.0 on 2021-12-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matthewsportfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Matthew Mohaghegh', max_length=255)),
                ('thumbnail', models.ImageField(default='images/IMG_1303.jpg', null=True, upload_to='')),
            ],
        ),
    ]
