# Generated by Django 4.0 on 2021-12-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matthewsportfolio', '0005_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(default='static/images/profile.png', null=True, upload_to=''),
        ),
    ]
