# Generated by Django 4.0 on 2021-12-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matthewsportfolio', '0008_person_more_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
