# Generated by Django 4.0 on 2021-12-14 08:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('matthewsportfolio', '0009_rename_content_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='matthewsportfolio.field'),
        ),
    ]
