# Generated by Django 4.0 on 2021-12-14 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matthewsportfolio', '0011_remove_person_name_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matthewsportfolio.field'),
        ),
    ]
