# Generated by Django 4.0 on 2021-12-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matthewsportfolio', '0015_alter_person_about_alter_person_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.TextField(blank=True, default='Lorem ipsum, dolor sit amet consectetur adipisicing elit.         Officiis porro itaque ipsum distinctio, inventore consequuntur nisi quis tenetur blanditiis illum quod voluptates.        Sit odit dolorum aperiam, deserunt veniam quia aut? Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti         alias, exercitationem atque obcaecati accusantium necessitatibus impedit delectus sequi?', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(default="I do a lot of crazy stuff with people's money!", max_length=400),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='Matthew', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='headline',
            field=models.CharField(default='portfolio Manager', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Mohaghegh', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='more_about',
            field=models.TextField(blank=True, default='Lorem ipsum, dolor sit amet consectetur adipisicing elit.         Officiis porro itaque ipsum distinctio, inventore consequuntur nisi quis tenetur blanditiis illum quod voluptates.        Sit odit dolorum aperiam, deserunt veniam quia aut? Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti         alias, exercitationem atque obcaecati accusantium necessitatibus impedit delectus sequi?', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(default='static/images/profile.png', null=True, upload_to=''),
        ),
    ]
