# Generated by Django 4.0 on 2021-12-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matthewsportfolio', '0017_alter_person_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, default='mailto:mattmohaghegh@gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram',
            field=models.CharField(blank=True, default='https://www.instagram.com/mattmohaghegh/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin',
            field=models.CharField(blank=True, default='https://www.linkedin.com/in/mattmohaghegh/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, default='tel:+15878324402', max_length=255, null=True),
        ),
    ]
